menu:
#- {name: 'lab', url: '/lab'}
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'talks', url: '/talks'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#lab:

people:
- {name: 'Chih-Yuan Yang 楊智淵', title: 'Assistant Professor', description: 'Expertise in computer vision and stock investing', department: 'Artificial Intelligence', institution: 'Chang Gung University', institution_address: 'No.259, Wenhua 1st Rd., Guishan Dist., Taoyuan City 33302, Taiwan (R.O.C.).', phone: '+886-3-2118800 #2543', email: 'cyyang@cgu.edu.tw', office: 'Management Building Room 1416', image: 'assets/img/Chih-Yuan_Yang.png', url: 'Chih-Yuan_Yang'}
- {name: 'Brian Liu 劉冠亨', title: 'Master student' , image: 'assets/img/Brian_Liu.jpg', description: 'Expertise in electronic engineering', url: 'Brian_Liu'}

courses:
- {name: '人工智慧概論 2024(醫學系A)', url: 'IntroToAI2024_medicine_A'}
- {name: '人工智慧概論 2024(職治系)', url: 'IntroToAI2024_occupational_therapy'}
- {name: '健康應用之程式語言 2024(呼治系)', url: 'HealthLanguage2024_respiratory_therapy'}
- {name: '健康應用之程式語言 2024(物治系)', url: 'HealthLanguage2024_physical_therapy'}
- {name: 'Computer Vision 2023', url: 'cv2023'}
- {name: 'Test', url: 'CallForPosters'}

talks:
- {name: 'Stock Investing at NTU iAgent lab', url: 'stock_investing_2303'}

social:
- {icon: 'github', link: 'https://github.com/yangchihyuan'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/yangchihyuan'}

contacts:
- {name: 'Chih-Yuan Yang Ph.D.', title: 'Assistant Professor', department: 'Artificial Intelligence', institution: 'Chang Gung University', institution_address: 'No.259, Wenhua 1st Rd., Guishan Dist., Taoyuan City 33302, Taiwan (R.O.C.).', phone: '+886-3-2118800 #2548', email: 'cyyang@cgu.edu.tw', office: 'Management Building B1416', image: 'assets/img/Chih-Yuan_Yang.png'}
